[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05537e4267d8f7bbeca77b3737967eadcd672fc6"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "2a70784df8004c2a0f31a9136da52d0c670b0246618a37e5bbce5061cf62ff7c"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e223a12bf4594f490f8517239afa29eafebe547"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "a510641673c4a31598727684258699d7323576d4552ecf92ae930ee133d30372"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04ea8235c5f40453a8dc3d7b424270610d40c4d3"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "851a592e14da264cd9ca1b48d6afdd98a50d1b2b13b9f0991e26cd130705f10d"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18adc9bfd2b3b0213f2eb16b99774f43f3f2f9cf"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "4222a75bc55bd986b0756192db5bd635a9beb940ceded328908761ec47577ac9"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95ebccee67b1a333333593fd19ef15f85d3f7748"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "1690f3bd466e4cb2e31b99b470a495cf23eb0a2f9be3ac199e4f65941dd4dd5c"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b81ae1e43f791c27c216076bb86e2536d3b0202d"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "f02510dd1dc17b119c63b93f954341115250290686f49ada434822b017dd226e"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abdef3234cd82260adeba7a88102d8d36b7fef93"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "0357cf433d26260e8dc34dadcfee3ea094edd91f5d454ab513ecf3c5dfd69144"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41c2bbb3a0ac196945caa28a100a3ebddbf18669"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "627ecec8d58a1d6a685623bb37c68ec1c052d884153357d87fec9beba6029882"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d3f4a175ffd4f8b8ba0dcee4fe4cf02ecafef9d"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "594719b71a26ff3565567168edb6db0b948280541fa2bec6577afe79fa04e05e"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3777830eca13b1334371d57b65dc4cfe6d3d2aa8"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "2932ead1b81819c3c7d6b6347e890d17e61c3ad72b5eb1c87eb701e2051e5c64"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dfdad0aea73ba537328252a676992651808fc1c"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "5373ad4ddb77ceb59df433811e7eb8195f969922a46c22eba0aece122f35cf3a"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "533bec0da54f73751cd6ae2404ddcef9bc32f6be"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "2cd7c724d6a1405237b106ad580bde4d340725d118f7c517e4c885909e439230"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f807f175f80fe865f433dd8050ec7476dab9c881"
os = "windows"

    [[Clipper.download]]
    sha256 = "32785348228dad6807f891869d869ea8d313399823990fe13228b1474b44ac78"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bae7e2f1f60f2d58da97fe8919e975a7799a79f2"
os = "windows"

    [[Clipper.download]]
    sha256 = "5944bac06ca53c02a48f701a8c940231daa949ba1ca8c39b5cbae1bbc4047c04"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2623b87da89e26862dfa49944d199d59ae8143fd"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "2967c122dee4a9a4163ba948302dace0cf65dd6c32485ff20e4a96253b199df5"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cd67314ab2e277f4d8010f4b63d0da341d98df"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "6d4456bbd93e9b26e0b3abddfa65a7d16545499c36645c0773e0b34b6bfc0f96"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "db4d92e94a20a8a016fff58637975d0352575ea7"
os = "macos"

    [[Clipper.download]]
    sha256 = "aba2c0bf5db9572ad98f39ea4856333f1c8aa1703f5d36c9815ba6a5474a7b4b"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-apple-darwin.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "749ab2cfb77117af6d973999a03d586c5740a549"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "287aa6965ee0463c97bff03e1c79610b1c36d11918b55ae3ed3dede364e9893f"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa25032a88913f5b3cfe140b09d783e929b62132"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "87455448465e9cd28b26338113b924ae8e6f359af3e92f227279762e4d967cbd"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cafd163b9acd628291345f434f46bb906da82c9"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "eb100cb50c0dee82528a207216d5aea642ac6dfecdefa0b87e0d27b92b3f82e1"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe97f6f7025e657eb6d4747bbc849f1cbcff0dcf"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "8a33f119e9c2e67fe9c2d23254d88043f6eb54a52302c32662f436bff94e054c"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "e3acfc727cd16e59cdfa2cb4bc738fa83f24cf87"
os = "freebsd"

    [[Clipper.download]]
    sha256 = "b8e028107a8da7d78d30cc038bc4743600f6afd280549b3b6a0ca1792834222f"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-unknown-freebsd.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "714b731968427751a9fe4d4c5f275d20e8f015a1"
os = "windows"

    [[Clipper.download]]
    sha256 = "0ad9b77884978a83c7746bfa4d6d14323b19194b6483a1ab19c174e82032f73f"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f59feb60a786159c03959d0e79ef32ae4965fba8"
os = "windows"

    [[Clipper.download]]
    sha256 = "1799a2568263975ba729ef0459aa399d7c59387bfacb13eb2ed246ff263be5f0"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+1/Clipper.v6.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
