[[Clipper]]
arch = "aarch64"
git-tree-sha1 = "a44818ddda744acd5f1a4c467aa8b368626a5146"
os = "macos"

    [[Clipper.download]]
    sha256 = "631bafd5c3b2d1dd85d34db92e9fbb7a2381345eb12e3e2c09e886ea176fe520"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.aarch64-apple-darwin.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87ca497c0f1761ae1afec65fb1c86210061c2ef7"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "41b9464534050145654a637c01bcd75829d1a635623bbdcb6ce3663a5a417e45"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c58ab83069721f2a124db159f56be798bd81d4e3"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "dc4f827eee65ce90d52c88d6a4cfc252c1ae69b88ea30228e467ff9941595547"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fd95052b419d84a551eab8eb2b5d8277d993b63"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "f83c46223bc16af24df8724646912dc09c17c8c0eb013e206ac4e5800bf03a9b"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.aarch64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36a7ad2f7f815aec92f6725199d6ec1846911cb3"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "70ac14606c5d38a096674a12dd6cca7e747e8c83698795d5694c6894fb852161"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.aarch64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "420f56be856214763c27001144072fae3a16aac0"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "65a7e10548aeb9ac9489e6bdc37f4af6aa1a2f00d4b82f0ba50e424d32f1c904"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce2305bf661e252c5bf4a60b3252f13e546f37eb"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "1cba5e0012112081e5e1dcd8158035bab70a2eedce04d140f1470fd9aaa53191"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clipper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08b16442d63213fb0719945c1cb651c58a51c239"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "8522561f2a2ba9358a64420d235d194b782a484e4c9faeac54d288843513e040"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f453a0689a4fec297fa29b1d4f9b807ecbd5d3b"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "50139276ad05ff9819971fba18ae12ac499c4f444d1b72cad311d5886511bbba"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cec883b9e45244342cb7c277dc40d1f28bfbbd9"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "1e9bd4decfb4c7dc4264a61a3d82d7731f36401d9173b2f667ffc6ef3bbc2a15"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb9f58c6a7b825774f366b09b7744164ee72dd36"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "d46f72772a608cd078b14180be7d217bc0da1fdc4ee1fb17aeb415ba9f589cb8"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5253ebe209782d56a93db702f2a781e83800b3d8"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "0bf80d1b4f82a35bb88eab19dae76dd42979fcc8f54531c03736c03bd5814c43"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "155623a2493ea7b87dd8a8aa2adfa252369394c3"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "5e51fb11660e41922613195be3f0e7eef87a329465eb9975993d8f2109eb9d57"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5354be3945f662c8c82db7d9b2499f4941e8ee9c"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "c8927b524a2ec0f026747621e13c6923050f8a52347b228040f6bdb51a3de2b4"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "036b68a53b357439d0cb66c9835f038d4cb8ac08"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "489d79306f95c6609d78387fef0e7a3cc62628cb340aabc2f465b31ce0c13930"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ba1fafd927d24b9c1b7f599592f3b768a9cc1d4"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "12e76fb9f69d8a305cefad90853a4d5efb57f62017cd6e2ac688b1d88f0b4550"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1746cca1c265a37580e6f4c101a7b0d032822f45"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "56afd2e866794b7762a15a491928be0b66180bc1c4547f556fc7349f8c210507"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a4c7480d4d9cb1b09e3ae0ac1ac5a5c8d9b55d1"
os = "windows"

    [[Clipper.download]]
    sha256 = "86f5b7e87aaee9fd219cd2541891a3446200f316695944a4ed459209a294a955"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3d60eea932c69fe9ae8d64f323562dc4a3e32b8"
os = "windows"

    [[Clipper.download]]
    sha256 = "931825f6e631afd7d33985d260052eaa38c1368bb63d1a59536fe37694b94e7a"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.i686-w64-mingw32-cxx11.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ed29176ec8e5fe8e8680fd55906aa4b8f2711cb"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "26a3d93bb059a79bed67efd14c429ac7b485c7486c093d73f967c507360620fb"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8376d175493fcb988effe994e9e2aa78c5337424"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "61e75cc38d67f83b5774e681c2b66ff8a670bc568e47cbbc95b508361af92e9a"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "c87fe4e78c057fb6e93224642fb4c5f8e6e5e640"
os = "macos"

    [[Clipper.download]]
    sha256 = "e7f97384beb2bbf98f92a76192c74c11a6c7bba139d11b08d0e85e995b29e8ef"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-apple-darwin.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5efe3e7d81bf4e7fc3cfa6b76a514fb12946b021"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "88549dbb9562903668ee52b1f9099b9eea11c3d5454c55f617aad0531518cdef"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b9fa3e1e526244adbc15de33d4582c4131b7cfa"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "ea6dd5f966fab3b27209cc4bd1e20ba8ba8eeb9e63d6ed955034e8f9eebb78bf"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fba5482b8c65082891003e07659a61483a3c7867"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "8f81fe9ec472a92a149ed430c2a95c243d07f0712ee293b220919cbf8ab761a0"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92a0a4f2368aaa46d1032f27ccbe6d9ef0aa2887"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "81d19f9be934423d133eb58f48d24f30bf02b048d9fdc4f0a7ec2da2f814fe55"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "617886aef8d33bc62c7ee8f5f3778d626602090a"
os = "freebsd"

    [[Clipper.download]]
    sha256 = "e3d94806220e966f1f7ebf414f18d29361d476c55dce928af58c5ddb08b7c641"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-unknown-freebsd.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dcc3f81cc5c288abf926972fc643fcbcbd706d79"
os = "windows"

    [[Clipper.download]]
    sha256 = "fa09b818f60ae091869aec535dbdf7315035d8263f08017eba5dad31a2d154b6"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "137fda8664ad2b91186eb126bdbbb66af87d65b1"
os = "windows"

    [[Clipper.download]]
    sha256 = "79f1fae8ab838054dde2f0d45778296ad1dff0b5a10f6794ee7e524e84a9b50c"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.3+0/Clipper.v6.4.3.x86_64-w64-mingw32-cxx11.tar.gz"
