[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "365a3dd7e2d424417ce836160d3774a87c950da6"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "ed7feee4e55b4e3a69b4e638e31b31f2504d9d106925d33423ce0ed568439625"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ac0547ac688fed4828c7c5aa2350fb01a68cd26"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "9688cee782205c76f33fcc766074c5aa2f6d277c38cb6dfdd674d0d1e1981910"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "114a2ba00fd7805b1341edb3ff7dd667e0e0522a"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "2387b43ff0243b35cb7daa368209c5890e5ec5e37d728644fc59d401985296ac"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2988f14ab19cb14f20420d24aeb39be7ad23c01f"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "4294b0a97694ab0df0c4f4a3128b380e44304d333aab94ddb7f1c6a70c6a049d"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "442a0498ad72ac5778a1bf384b34f602d794d8c1"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "ee7fce4b0540a1647079a64f2de198fad4bb402fd7d7caeee93d2688a1103a8f"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb48d4e95c251f1b21f180253369c2daa27583dc"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "b896e9e8c7d87c07bbbf640779c3a7998ed9ef832b7b3fdc367c3a0cf27e3496"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdb2003f10c143743547683a5049b6f839594333"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "80aae778a264136946169d010ce89f1f17139e4e9c8ae53d59ab7a37525c4014"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clipper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d633e455b44e644f6151c315589c5fda0242c10"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "f3763cbc3c83599f065aa58a3f2c57c348b0a62438acd3a5e4439430e7760e88"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cffa977dc4a81b2a7fadca404e9320dfce812d6"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "7daf33d52d820e598d456b18e3b6e0d43abfe4b5b8ffa9310fdad64ba3967399"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1519c73436fd3cbbb53d5518d5003a0ce3111a6a"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "1f62b3948963d38065f21f8255d7f6c1917567ca1315c2c8ee4562454a1ad900"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4727dc635a3fb7e753d4d838ae313bd645cc3c60"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "ee93f37b9cac6b0e6a99e6c9ab2babb97b0a964389c5a3107aee3d3ec7b786d1"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a00bd41488e2692f591bb17162cb685316c096b"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "80f9e89cabdd96cc7e5e9bca2a661ee08d6ba62ec421318815125ddc3afb9434"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe04bb2ed758edbd7427f308b82546bfd3bed6a1"
os = "windows"

    [[Clipper.download]]
    sha256 = "a8f78fa71e956ff803a8041b295a4399f1ca1431b03da9a659639efbc935a5d3"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76bfb3402fdae7ff2c9f6e8a26d4cd614693d0d3"
os = "windows"

    [[Clipper.download]]
    sha256 = "6d29776025e6fcefc048f8348406684c85634f5080d858def4db90a2ad56a10c"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f744833886c8866770778e2c44c725c97cc3b4ad"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "0bb4fd2e05f23b2bdb3a53db45f5643de07ae45cde5946d57c94a9bce803f146"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a15b654e24d89f5001e96856e495c6b66d0a2925"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "8a869a120562bbd10b6143be7f19f2742ef2db67b4937b0d8409255db4c0eb42"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "7c40ee53a8ddbfc4cc16d47a0f367168a288159f"
os = "macos"

    [[Clipper.download]]
    sha256 = "4b4e7d5848192314c265bed3b44ae3ce5bbe4b2e6aa6b45e9dc5c30c7e760a0f"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-apple-darwin.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "59d9212f869c09b08855415e4e3764bcc01816de"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "5ab405ef824bb6d96c8be440ad7ce07e990d05f1a534163d3c9506d4f8c55314"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bc86a5f29d273a8fa4c63d9c8b30f67c944b90d"
libc = "glibc"
os = "linux"

    [[Clipper.download]]
    sha256 = "8af95554d0faa4c3a7247812875aaa8e5564d69edc1979e8c6e1d12fdce68bc5"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a2215e1f3a1a07c33f2d4bbfcf2f687d9baba3"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "b4c4f300f14f0d2151d8057c1fa0c532b4c6d83ece2dda02dd4573966b38acbc"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8490564181e82545ac5a8175c876350648ab4146"
libc = "musl"
os = "linux"

    [[Clipper.download]]
    sha256 = "b70f1ed4488fd784dc6d4b9b00a85c9c13e9048424d3acf53287f0f3bfc3cb83"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[Clipper]]
arch = "x86_64"
git-tree-sha1 = "e6ea7b1a33ec88c968d2cec9b3d61d8587a6eb1b"
os = "freebsd"

    [[Clipper.download]]
    sha256 = "496e1ec6db20426cb7c943eda58f8369c8be8edb76b449c1835e43759221cca3"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-unknown-freebsd.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb7060f9034413adb24cc7bad01b41720aee5091"
os = "windows"

    [[Clipper.download]]
    sha256 = "283c6c0c014d159e99293ae17ebd90650648ee6d8fc2b48c9286f6eca7f2dc5b"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clipper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33f41df3c1e61c65146f2d1300e6797bbd6966cd"
os = "windows"

    [[Clipper.download]]
    sha256 = "2950f95c805eb42d2e47d39b73712bf4ddc9093d90a011e005ce8e21f0046c55"
    url = "https://github.com/JuliaBinaryWrappers/Clipper_jll.jl/releases/download/Clipper-v6.4.2+0/Clipper.v6.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
